apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/persistentvolumeclaim.yaml
- manifests/statefulset.yaml
- manifests/back-config.yaml
- manifests/backend-deployment.yaml
- manifests/backend-service.yaml
- manifests/frontend-deployment.yaml
- manifests/frontend-service.yaml
secretGenerator:
- files:
  - POSTGRES_PASSWORD
  name: db-password
  namespace: project
  type: Opaque
configMapGenerator:
- files:
  - GRAPHQL_URL
  name: front-config
  namespace: project 
- files:
  - NEW_NS
  name: back-ns-config
  namespace: project