apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: file-claim
      containers:
        - name: dwk-frontend
          image: FRONTPROJECT/IMAGE      
          volumeMounts:
          - name: shared-files
            mountPath: /usr/src/app/shared