apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: file-claim
      containers:
        - name: dwk-frontend
          image: FRONTPROJECT/IMAGE
          resources:
            limits:
              cpu: "200m" # limit "m" stands for "thousandth of a core"
              memory: "100Mi"
          env:
            - name: GRAPHQL_URL
              valueFrom:
                configMapKeyRef:
                  name: front-config # this is ConfigMap Name
                  key: GRAPHQL_URL # this is key in ConfigMap      
          volumeMounts:
          - name: shared-files
            mountPath: /usr/src/app/shared