apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: project
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000
      name: frontend