name: Project release  

on:
  push:

env:
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-west6-a
  DB_IMAGE: dwk-db
  BACK_IMAGE: dwk-backend
  FRONT_IMAGE: dwk-frontend
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true  
   
jobs:
  setup-build-deploy:
    name: Setup, Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create image names and tags
      run: |-
        my_ref=${GITHUB_REF:10} # removes first 10 characters from ref/heads/<branch> or ref/tags/<tagname>
        new_ref=${my_ref#/} # removes the remaining / in case of branch name
        new_ref=${new_ref//./-} # replaces eventual dots with hyphens (e.g. in a tag) so that it is good for namespace
        echo "::set-env name=DB_IMAGE_WITH_TAG::gcr.io/${{ secrets.GKE_PROJECT }}/$DB_IMAGE:$new_ref-$GITHUB_SHA"   
        echo "::set-env name=BACK_IMAGE_WITH_TAG::gcr.io/${{ secrets.GKE_PROJECT }}/$BACK_IMAGE:$new_ref-$GITHUB_SHA"   
        echo "::set-env name=FRONT_IMAGE_WITH_TAG::gcr.io/${{ secrets.GKE_PROJECT }}/$FRONT_IMAGE:$new_ref-$GITHUB_SHA"      
            
    - name: Setup gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
    
    - name: Configure docker
      run: gcloud --quiet auth configure-docker

    - name: Get credentials
      run: |-
        echo $GKE_CLUSTER
        echo $GKE_ZONE
        gcloud auth list
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE
        
    - name: Build
      run: |-
        cd db
        docker build --tag "$DB_IMAGE_WITH_TAG" .
        cd ../backend
        docker build --tag "$BACK_IMAGE_WITH_TAG" .
        cd ../frontend
        docker build --tag "$FRONT_IMAGE_WITH_TAG" .

    - name: Publish
      run: |-
        docker push "$DB_IMAGE_WITH_TAG"
        docker push "$BACK_IMAGE_WITH_TAG" 
        docker push "$FRONT_IMAGE_WITH_TAG"

    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
        pwd
        ls -l

    - name: Deploy
      run: |-
        export PASSWORD_FROMGITHUB=${{ secrets.DB_PWD }}
        echo -n $PASSWORD_FROMGITHUB > POSTGRES_PASSWORD
        my_ref=${GITHUB_REF:10} 
        new_ref=${my_ref#/} 
        NEW_NS=${new_ref//./-}
        echo -n "http://backend-svc.$NEW_NS.svc/graphql" > GRAPHQL_URL
        echo -n $NEW_NS > NEW_NS
        kubectl create namespace $NEW_NS || true
        ./kustomize edit set namespace $NEW_NS
        ./kustomize edit set image DBPROJECT/IMAGE=$DB_IMAGE_WITH_TAG
        ./kustomize edit set image BACKPROJECT/IMAGE=$BACK_IMAGE_WITH_TAG 
        ./kustomize edit set image FRONTPROJECT/IMAGE=$FRONT_IMAGE_WITH_TAG 
        kubectl apply -k .
        kubectl rollout status statefulset/postgres-ss -n $NEW_NS
